enhancement:
  - "features/*"
  - "feature/*"
  - "feat/*"
  - "features-*"
  - "feature-*"
  - "feat-*"
bug:
  - "fixes/*"
  - "fix/*"
  - "fixes-*"
  - "fix-*"
  - "bugs/*"
  - "bugs-*"
  - "bug-*"
chore:
  - "chore/*"
  - "chore-*"
  - "update/*"
  - "update-*"
dependencies:
  - "update/*"
  - "update-*"
  - "bump/*"
  - "bump-*"
