repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-added-large-files
  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
  # Python's import formatter
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # Automatically upgrade syntax for newer versions of Python language
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  # Automatically remove unused builtins imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
  # Python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--append-config", ".flake8"]
  # Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  # Python tool for docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args:
          [
            "--config",
            "pyproject.toml",
            "--generate-badge",
            "./badges",
            "--badge-style",
            "flat",
          ]
        pass_filenames: false
  # Python tool for docstring style checker
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          [
            "--ignore",
            "D100,D200,D202,D203,D205,D212,D400,D401,D406,D407,D413,D415",
            "--match-dir",
            "^(?!\\..*|test).*",
          ]
        additional_dependencies: ["tomli"]
        exclude: "tests"
  # Formatter for Json and Yaml files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [json, yaml, toml]
  # Formatter for shell scripts
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt
  # Linter for shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args: ["--exclude", "1090"]
  # Formatter for markdown files
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat-frontmatter
          - mdformat-black
          - mdformat-shfmt
