# Apply interrogate and generate its badge when a push or a PR occurs
name: Interrogate codebase for docstring coverage
on: [push, pull_request]
jobs:
  interrogate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install interrogate
        run: pip install interrogate
      - name: Run interrogate
        run: interrogate --generate-badge ./badges --badge-style flat
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add badges/interrogate_badge.svg
          git diff --exit-code || git commit -m "Update interrogate_badge.svg" -a
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
