# Apply interrogate and generate its badge when a push or a PR occurs
name: Interrogate codebase for docstring coverage
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  interrogate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install interrogate
        run: pip install interrogate
      - name: Run interrogate
        run: interrogate --generate-badge ./badges --badge-style flat || true
      - name: Check changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v35.5.0
        with:
          files: badges
      - name: Commit files
        if: steps.verify-changed-files.outputs.any_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update interrogate_badge.svg"
      - name: Push changes
        if: steps.verify-changed-files.outputs.any_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
