# Auto create a Pull Request when a push is made and label it
name: PR auto

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if PR exists
        id: check
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --head ${{ github.ref_name }} \
              --base ${{ github.event.repository.default_branch }} \
              --json title \
              --jq 'length')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create PR
        if: ${{ !steps.check.outputs.skip }}
        run: |
          gh pr create \
          --head ${{ github.ref_name }} \
          --base ${{ github.event.repository.default_branch }} \
          --title ${{ github.ref_name }} --body '' --draft
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ github.token }}
