# Auto create a Pull Request when a push is made
name: PR autocreate

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create PR
        run: gh pr create -B ${{ github.event.repository.default_branch }} -H ${{ github.ref_name }}
          --title ${{ github.ref_name }} --body ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
