# This workflow finds which files were changed, prints them, and runs `pre-commit` on those files.
# Inspired by ashleve's lightnight-hydra-template repository:
# https://github.com/ashleve/lightning-hydra-template/blob/main/.github/workflows/code-quality-pr.yaml
name: PR Code Quality
on:
  pull_request:
    branches: [main, "master", "release/*", "dev"]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Find modified files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "
      - name: List modified files
        run: echo '${{ steps.file_changes.outputs.files }}'
      - name: Run pre-commits
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }}
