# This workflow will apply the corresponding label on a pull request
name: PR Labeler

on:
  pull_request_target:
  workflow_run:
    workflows:
      - PR autocreate
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ github.token }}
