name: Pre-commit auto-update
on:
  # every sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
